### PR TITLE
add Fetch polyfill

### PR DESCRIPTION
**Pull request by pcanterini**
Added support for other browsers using https://github.com/github/fetch
Should probably have asked before opening a PR but feel free to just close in case not interested.

Thanks for sharing.

### CODE REVIEW

**Comment by yildizberkay** [comment]
Hey Pedro, thank you for your PR, It works very well :)

**Comment by pcanterini** [comment]
@yildizberkay np!
I totally forgot to update the notice you have in the README file.

Would you like me to send a PR for that or would you prefer to reword it yourself to something you think makes sense?

**Comment by yildizberkay** [comment]
Readme and demo page were updated. Moreover, I created a [changelog](https://github.com/yildizberkay/redux-example#changelog) section.

**Comment by pcanterini** [comment]
Awesome :+1:

**Pull request merged**
